# compose.base.yml 
#
# partially configured services 
# deploy in both test and prod
services:

  db:
    container_name: pwsite-${ENV}-db
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/New_York
    volumes:
      - pwsite-${ENV}-db-data:/var/lib/postgresql

  app:
    container_name: pwsite-${ENV}-app
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    environment:
      - ENV=${ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - TZ=America/New_York
    depends_on:
      - db

networks:
  default:
    name: pwsite-${ENV}-net

volumes:
  db-data:
    name: pwsite-${ENV}-db-data

