# compose.yaml
services:
  
  app:
    container_name: pwsite-${ENV}-app
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    environment:
      - API_URL=${API_URL}
      - TZ=America/New_York
    depends_on:
      - backend

  admin:
    container_name: pwsite-${ENV}-admin
    build: 
      context: ./admin
      args:
        # tell non ssl admin ui its origin so it c
        # can do svelte server side actions
        # different for test/prod
        PORT: ${ADMIN_PORT}
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT}:3000"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - backend

  backend:
    container_name: pwsite-${ENV}-backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8080" # could remove later?
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable

  db:
    container_name: pwsite-${ENV}-db
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432" # could remove later?
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/New_York
    volumes:
      - db-data:/var/lib/postgresql

networks:
  default:
    name: pwsite-${ENV}-net

volumes:
  db-data:
    name: pwsite-${ENV}-db-data
