name: Build & Deploy Frontend

on:
  push:
    branches:
      - main # prod
      - test
    paths:
      - "admin/**"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"

      # set api URL
      # for dev, this should be localhost:<backend port>
      # for test, <backend container name>:<internal port (8080)>
      # for prod, same as test.  Not sure abt this yet tho
      API_URL: 'http://backend:8080'
      
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Admin Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./admin
          file: ./admin/Dockerfile
          push: false
          tags: app:latest

      - name: Restart Admin Frontend Service
        run: |
          docker compose up -d --no-deps --build admin
