name: Build & Deploy Backend

on:
  push:
    branches:
      - main # prod
      - test
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - "compose.yaml"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"
      
      BACKEND_PORT: ${{ vars.BACKEND_PORT }}

      # postgres vars required by compose file to make DATABASE_URL
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # not publishing to a registry
          tags: backend:latest

      - name: Restart Backend Service
        run: |
          docker compose up -d --no-deps --build backend
