name: Deploy Database & Migrate

on:
  push:
    branches:
      - main # prod
      - test
    paths:
      - "backend/migrations/**"
      - "backend/schema.hcl"
      - ".github/workflows/database.yml"

jobs:
  migrate-db:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      
      # need to set up db container
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

      # pass this to migration command
      DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DB }}?sslmode=disable"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Database Container
        run: |
          docker compose up -d db
          echo "Waiting for Postgres to be ready..."
          sleep 5

      - name: Run Migrations via Atlas
        run: |
          docker run --rm \
            --network pwsite-${ENV}-net \
            -v ./backend/migrations:/migrations \
            arigaio/atlas:latest \
            migrate apply \
            --dir "file:///migrations" \
            --url ${DATABASE_URL}

