name: Deploy App

on:
  push:
    branches:
      - main # prod
      - test
    # don't deploy on non code changes
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - '*.example'
      - '.gitignore'

jobs:
  deploy:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      APP_PORT: ${{ vars.APP_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      PROXY_NET: 'nathan_default'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker compose -f compose.yaml build \
            --build-arg DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}
      
      - name: Start containers
        run: docker compose -f compose.yaml up -d --remove-orphans

      - name: Connect App container to proxy network (prod only)
        if: env.ENV == 'prod'
        run: docker network connect ${PROXY_NET} pwsite-prod-app

      - name: Cleanup unused images
        run: docker image prune -f
