name: Build & Deploy Frontend

on:
  push:
    branches:
      - main # prod
      - test
    paths-ignore:
      - 'backend/**'
      - 'README.md'
      - '**/README.md'
      - '*.example'
      - '.gitignore'
      - '.github/workflows/backend.yml'
      - '.github/workflows/database.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    # set which env to pull secrets/vars from
    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      APP_PORT: ${{ vars.APP_PORT }}
      COMPOSE_PROJECT_NAME: "pwsite-${{ github.ref_name == 'main' && 'prod' || 'test' }}"

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: app:latest
          build-args: |
            API_URL=${{ github.ref_name == 'main' && 'https://nklein.xyz/api' || 'http://atlas:8082' }}

      - name: Restart Frontend Service
        run: |
          docker compose up -d --no-deps --build app
